name: pipeline

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -V
      - name: Build
        run: echo "Build-job executado com sucesso :)"

  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 app.py
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "python"



