name: CI

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update
      - name: Build
        run: echo "Build-job executado com sucesso :)"

  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: apt-get install nginx -y
      - uses: AppThreat/sast-scan-action@master


  deploy-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER__TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: usuariodocker/repositorio:tag

      - name: Deploy
        run: echo  "Deploy-job executado com sucesso :)""
